(function() {var implementors = {};
implementors["wayland_client"] = ["impl&lt;I:&nbsp;<a class=\"trait\" href=\"wayland_commons/trait.Interface.html\" title=\"trait wayland_commons::Interface\">Interface</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"wayland_client/struct.Proxy.html\" title=\"struct wayland_client::Proxy\">Proxy</a>&lt;I&gt;","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"wayland_client/egl/struct.WlEglSurface.html\" title=\"struct wayland_client::egl::WlEglSurface\">WlEglSurface</a>",];
implementors["wayland_server"] = ["impl&lt;I:&nbsp;<a class=\"trait\" href=\"wayland_commons/trait.Interface.html\" title=\"trait wayland_commons::Interface\">Interface</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"wayland_server/struct.Resource.html\" title=\"struct wayland_server::Resource\">Resource</a>&lt;I&gt;",];
implementors["wayland_sys"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"wayland_sys/client/struct.WaylandClient.html\" title=\"struct wayland_sys::client::WaylandClient\">WaylandClient</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"wayland_sys/server/struct.WaylandServer.html\" title=\"struct wayland_sys::server::WaylandServer\">WaylandServer</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"wayland_sys/egl/struct.WaylandEgl.html\" title=\"struct wayland_sys::egl::WaylandEgl\">WaylandEgl</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"wayland_sys/cursor/struct.WaylandCursor.html\" title=\"struct wayland_sys::cursor::WaylandCursor\">WaylandCursor</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
